# Generated by Django 4.0.5 on 2022-06-21 07:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobposting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=100)),
                ('reward', models.IntegerField()),
                ('content', models.TextField()),
                ('skill', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'db_table': 'jobpostings',
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobposting.jobposting')),
            ],
            options={
                'db_table': 'details',
            },
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('apply_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('jobposting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobposting.jobposting')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'applies',
            },
        ),
    ]
