# Generated by Django 4.0.5 on 2022-06-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('jobposting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='applys',
            field=models.ManyToManyField(blank=True, null=True, related_name='jobpostings', through='jobposting.Apply', to='user.user'),
        ),
    ]
