# Generated by Django 4.0.5 on 2022-06-21 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobposting', '0002_jobposting_applys'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='apply',
            table='apply',
        ),
        migrations.AlterModelTable(
            name='detail',
            table='detail',
        ),
        migrations.AlterModelTable(
            name='jobposting',
            table='jobposting',
        ),
    ]
