# Generated by Django 4.0.5 on 2022-06-26 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobposting', '0003_alter_apply_table_alter_detail_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobposting',
            old_name='name',
            new_name='company',
        ),
    ]
