# Generated by Django 4.0.5 on 2022-06-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobposting', '0004_rename_name_jobposting_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='apply_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='apply',
            constraint=models.UniqueConstraint(fields=('user_id', 'jobposting_id'), name='apply only once constraint'),
        ),
        migrations.AlterModelTable(
            name='apply',
            table=None,
        ),
    ]
