# Generated by Django 4.0.5 on 2022-07-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobposting', '0005_alter_apply_apply_at_alter_apply_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='applys',
        ),
        migrations.AlterField(
            model_name='apply',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
